layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

repository: mcneilllucy/mcneilllucy.github.io

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

#projects:
#  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
#  limit: 9
#  exclude:
#    archived: false
#    forks: true
#    projects:
    # - repo-name

# social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: arXiv
    web_url: https://arxiv.org/search/?searchtype=author&query=McNeill%2C+L+O
    image_url: https://pbs.twimg.com/media/EcglfCHU4AA6-yj.png:large

  - name: Mathematica notebooks
    web_url: https://github.com/mcneilllucy/mcneilllucy.github.io/tree/master/assets/mathematica-notebooks
    image_url: https://community.wolfram.com//c/portal/getImageAttachment?filename=wolframwolf.png&userId=1340903

  - name: Notes
    web_url: https://github.com/mcneilllucy/mcneilllucy.github.io/tree/master/assets/notes
    image_url: https://prosportstickers.219signs.com/image/cache/catalog/product/homer_thinking_sticker__46595-500x500.jpg

  - name: synapsis
    web_url: http://bioconductor.org/packages/release/bioc/html/synapsis.html
    image_url: https://github.com/mcneilllucy/mcneilllucy.github.io/blob/master/assets/images/synapsis_hexsticker.PNG



BASE_PATH : /mcneilllucy.github.io
